---
title: "comperhansive analysis"
author: "YOU & SHENG"
date: "November 21, 2017"
output: pdf_document
---

```{r}
library(plyr)
actors1 = read.csv("actors_score.csv")
actors2 = read.csv("actors_score.csv")
actors = plyr::join(read.csv("actors_score.csv")[,2:3],
                    read.csv("actors_gross.csv")[,2:3],
                    type = "left", 
                    by = "actors")

keywords = plyr::join(read.csv("keywords_score.csv")[,2:3],
                      read.csv("keywords_gross.csv")[,2:3],
                      type = "right", 
                      by = "keywords")
directors = plyr::join(read.csv("directors_score.csv")[,2:3],
                       read.csv("directors_gross.csv")[,2:3],
                       type = "right", 
                       by = "directors")
genres_score = read.csv("genres_score.csv")[,2:3] 
genres_gross = read.csv("genres_gross.csv")[,2:3]
colnames(genres_score)=c("genres","score.coef")
genres = plyr::join(genres_score,
                    genres_gross,
                    type = "right", 
                    by = "genres")
```

```{r}
genres_arrange=genres %>%
  dplyr::arrange(desc(gross_coef,score.coef))
genres_gross=genres %>%
  dplyr::arrange(desc(gross_coef))
genres_score=genres %>%
  dplyr::arrange(desc(score.coef))


genres_arrange
genres_gross
genres_score
```

```{r}
keywords_arrange=keywords %>%
  dplyr::arrange(desc(gross_coef,score_coef))
keywords_gross=keywords %>%
  dplyr::arrange(desc(gross_coef))
keywords_score=keywords %>%
  dplyr::arrange(desc(score_coef))

keywords_arrange
keywords_gross
keywords_score
```

```{r}
actors_arrange=actors %>%
  dplyr::arrange(desc(gross_coef,score_coef))
actors_gross=actors %>%
  dplyr::arrange(desc(gross_coef))
actors_score=actors %>%
  dplyr::arrange(desc(score_coef))


actors_arrange
actors_gross
actors_score
```

```{r}
directors_arrange=directors %>%
  dplyr::arrange(desc(gross_coef,score_coef))
directors_gross=directors %>%
  dplyr::arrange(desc(gross_coef))
directors_score=directors %>%
  dplyr::arrange(desc(score_coef))


directors_arrange
directors_gross
directors_score
```
```

